apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: calc-web-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: REDIS_HOST
          value: "redis"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: DB_NAME
          value: "calc_db"
        - name: DB_USER
          value: "admin"
        - name: RABBITMQ_USER
          value: "admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calc-secrets
              key: postgres-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calc-secrets
              key: redis-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calc-secrets
              key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 32500
  selector:
    app: web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-worker
  template:
    metadata:
      labels:
        app: calc-worker
    spec:
      containers:
      - name: calc-worker
        image: calc-worker:latest
        imagePullPolicy: Never
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: REDIS_HOST
          value: "redis"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: DB_NAME
          value: "calc_db"
        - name: DB_USER
          value: "admin"
        - name: RABBITMQ_USER
          value: "admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calc-secrets
              key: postgres-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calc-secrets
              key: redis-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calc-secrets
              key: rabbitmq-password
